# -*- coding: utf-8 -*-
"""Assignment-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LD-O8OvFC1SKKwY-c85STSD0wbePAdZo
"""

def calculate_electricity_bill(previous_unit, current_unit, customer_type, rate_per_unit,
                                fixed_charge, customer_charge, electricity_duty_percentage):
    units_consumed = current_unit - previous_unit

    if units_consumed < 0:
        print("Error: Current unit cannot be less than previous unit.")
        return

    energy_charges = units_consumed * rate_per_unit

    # Electricity Duty is now a percentage of Energy Charges as per previous example
    electricity_duty = energy_charges * (electricity_duty_percentage / 100)

    # Total Bill now sums all provided charges
    total_bill = energy_charges + fixed_charge + customer_charge + electricity_duty

    print(f"\n-- BILL SUMMARY --")
    print(f"Customer Type: {customer_type.capitalize()}")
    print(f"Units Consumed: {units_consumed:.2f}")
    print(f"EC (Energy Charges): {energy_charges:.2f}")
    print(f"FC (Fixed Charges): {fixed_charge:.2f}")
    print(f"CC (Customer Charges): {customer_charge:.2f}")
    print(f"ED (Electricity Duty): {electricity_duty:.2f}")
    print(f"Total Bill: {total_bill:.2f}\n")

# --- Application Start ---
print("Welcome to the TGNPDCL Bill Generator!")

try:
    pu = int(input("Enter Previous Unit Reading (PU): "))
    cu = int(input("Enter Current Unit Reading (CU): "))
    customer_type_input = input("Enter Type of Customer (Domestic/Commercial): ")
    rate_per_unit_input = float(input("Enter Rate per Unit: "))
    fixed_charge_input = float(input("Enter Fixed Charge: "))
    customer_charge_input = float(input("Enter Customer Charge: "))
    electricity_duty_percentage_input = float(input("Enter Electricity Duty (%): "))

    calculate_electricity_bill(pu, cu, customer_type_input,
                               rate_per_unit_input, fixed_charge_input,
                               customer_charge_input, electricity_duty_percentage_input)
except ValueError:
    print("Invalid input. Please ensure numbers are entered for unit readings, rates, and charges, and a valid customer type.")